image: node:20

definitions:
  caches:
    pnpm: ~/.pnpm-store

pipelines:
  default:
    - step:
        name: Install, Validate & Build
        caches:
          - pnpm
        script:
          - corepack enable
          - corepack prepare pnpm@latest --activate
          - pnpm install --frozen-lockfile
          - pnpm turbo run lint
          - pnpm turbo run build